basePath: /api/v1
definitions:
  main.developer:
    properties:
      id:
        type: integer
      language:
        type: string
      name:
        type: string
    type: object
host: localhost:7070
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /dev:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.developer'
            type: array
        "404":
          description: Not Found
          schema:
            items:
              $ref: '#/definitions/main.developer'
            type: array
      summary: ping dev
      tags:
      - example
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
